---
title             : "New Lab 8 Title"
shorttitle        : "lab8"

author: 
  - name          : "Angela Lee"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "1451 Onyx Street, Eugene, OR 97403"
    email         : "alee12@uoregon.edu"
  - name          : "Ruby Cuellar"
    affiliation   : "1"
  - name          : "Ellen Huang"
    affiliation   : "1"

affiliation:
  - id            : "1"
    institution   : "University of Oregon"


abstract: |
  Soon our _**awesome**_ abstract will go here. 
  

keywords          : "psychology, rmarkdown, data science"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
library(knitr)
library("papaja")
library(ggplot2)
library(here)
library(rio)
library(janitor)
library(dplyr)
opts_chunk$set(echo = FALSE, fig.width = 6.5, fig.height = 8)
```

```{r data import}
data<-import(here("data","star.csv")) %>% 
  clean_names()
```



# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
